apiVersion: v1
kind: Pod
metadata:
  name: init-agent
  namespace: project-foo
spec:
  containers:
  - image: jaysson1710/init-agent:latest
    name: init-agent
    env:
        - name: AZP_TOKEN
          value: 3xnmxan7imq6fv5byxgsovesnotb6a75xmbmhvoqllxnogg3fc3q
        - name: AZP_URL
          value: https://jaysson1710.visualstudio.com/
        - name: AZP_POOL
          value: default
    resources:
      requests:
        cpu: 300m
        memory: 300Mi
      limits:
        cpu: 500m
        memory: 500Mi
    readinessProbe:
        exec:
            command:
                - /bin/sh
                - -c
                - "cat /azp/agent/_diag/Agent_*.log | grep \"Listening for Jobs\""
        initialDelaySeconds: 15
        periodSeconds: 5
  